Feature
Adanzeakonobi/My-Portfolio-project-2 pull request #1
Opened 2022-03-17 17:12 UTC by Adanzeakonobi

2022-03-17 17:32 UTC, xtrahuman requested changes
Hi @Adanzeakonobi , 

You have made a great effort in this project but unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no descriptive pull request, Kindly make sure your pull request has a well-descriptive title and content it enables the reviewer to know the progress you made on the project.

Also, kindly fix some errors in your README, the title of the project was mentioned twice

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-03-17 20:23 UTC, BenMukebo requested changes
## Hi *** @Adanzeakonobi, ***

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

### To highlight 💪🏻

- No linter errors. ✔️ 
- Github flow was correctly used.  ✔️   
- Good commit messages ✔️ 
- Professional README ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the  [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 20:23 UTC, BenMukebo commented on index.html
> +        </div>
- [ ] Great work on your project, you have done a great job, however, I think we will need to make a few changes on this section before you go onto the next step, Kindly change the `div` tag on line 31 to a `ul` tag instead and wrap its entire elements, each `a` tag in a `li` tag. 
- [ ] Please match your web app with the same `color, padding, margin, font-weight, font-height` to the original one.
- [ ] Consider adjusting your hamburger icon which is duplicated many times
- [ ] Kindly remove the white spaces shown below
- [ ] Actually you `h1` title is underline in blue , please `use text-decoration: none` to fix it
- [ YOUR DESIGN] 
<img width="318" alt="biz" src="https://user-images.githubusercontent.com/79058364/158888232-70a61d96-265a-4ae8-81fc-0b9131d2a757.png">

- [ FIGMA DESIGN]
<img width="294" alt="blackfug" src="https://user-images.githubusercontent.com/79058364/158888352-0df312cb-1f38-49a5-b4a7-adc0c0cb38ec.png">

2022-03-17 20:23 UTC, BenMukebo commented on index.html
> +      <a href="#" class="navbar-logo">Adaobi Okoye</a>
- [ ] Your logo is underlined, please set `text-decoration: none` to fix this

2022-03-18 00:31 UTC, keroloussamy requested changes
Hi @Adanzeakonobi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 00:31 UTC, keroloussamy commented on index.html
> +      </a>
- [ ] Kindly When you were making the changes, you changed the path of the image by mistake. Kindly return it to `src="Icons/Union.png"`.

2022-03-18 00:31 UTC, keroloussamy commented on index.html
> +            </a>
- [ ] Kindly when you were making the changes, you changed the path of the image by mistake. Kindly return it to `src="Icons/linkedin icon.png"`.

2022-03-18 00:31 UTC, keroloussamy commented on style.css
> +
- [ ] Kindly remove the `height: 600px;` role, to remove the white space at the bottom, as required by the previous reviewer.

![image](https://user-images.githubusercontent.com/35535130/158914448-17813183-9cc9-467a-9987-c9bc806cc3cf.png)

2022-03-18 00:31 UTC, keroloussamy commented on style.css
> +}
- [ ] Kindly remove `width: 98%;` and `padding: 10px;` from here, to solve the white space on the left issue, as required by the previous reviewer.

![image](https://user-images.githubusercontent.com/35535130/158914857-e0045181-663e-413d-a966-cc4d2142ea22.png)

2022-03-18 00:31 UTC, keroloussamy commented on style.css
> +}
- [ ] Continuing to solve the left white space, remove `padding-right: 50px;` from here too.

2022-03-18 16:40 UTC, vic778 requested changes
### STATUS: CHANGES REQUIRED :yellow_circle: 
Hi @Adanzeakonobi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Project highlights:
- [x] All linter checks are passing :heavy_check_mark: 
- [x] Descriptive commits and correct use of the Git Flow :fire:
- [x] :white_check_mark: page titles :white_check_mark: text headings :white_check_mark: color contrast :white_check_mark: resize :white_check_mark: basic structure of the page 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


![so close](https://c.tenor.com/nMbdSNsg_jsAAAAC/the-simpsons-homer-simpson.gif)

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 16:40 UTC, vic778 commented on index.html
> +        <img src="/Icons/Union.png" alt="Menu"/>
kindly change the location of your files. instead of `/Icons/Union.png"` use `icons/Union.png"` and it will work

2022-03-18 16:40 UTC, vic778 commented on index.html
> +        </ul>
kindly change the location of your files. instead of `/Icons/Union.png"` use `icons/..."` followed by the name of tour icon and it will work

2022-03-18 17:54 UTC, sinansevgi reviewed
Hello @Adanzeakonobi  👋,

_This is an additional review as a result of the second opinion request._

Looks like the image issue is resolved 👍 

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please note that since we will approve it manually so this could take few hours!

Keep rocking 🚀!

2022-03-19 08:20 UTC, merged

2022-03-19 23:46 UTC, Adanzeakonobi commented
Hello Sinansevgi,

Trust you are doing okay.
This is to inform you that this project is yet to be approved.
Please could you help look into it?

Thank you.
Best Regards.

On Fri, Mar 18, 2022 at 11:55 AM Sinan Sevgi ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Hello @Adanzeakonobi <https://github.com/Adanzeakonobi> 👋,
>
> *This is an additional review as a result of the second opinion request.*
>
> Looks like the image issue is resolved 👍
>
> As this was the only reason that your project was not approved it will be
> approved as soon as possible.
> Please note that since we will approve it manually so this could take few
> hours!
>
> Keep rocking 🚀!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Adanzeakonobi/My-Portfolio-project-2/pull/1#pullrequestreview-914691962>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXFYVBJMWKOTT4JPNMF2JQTVAS7PPANCNFSM5Q7PD4CA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>